services:
  app_frontend:
    build:
      context: ./culturalevents-frontend
      dockerfile: Dockerfile
    container_name: app-cultural-events-frontend
    ports:
      - "4200:80"
    depends_on:
      app_backend:
        condition: service_healthy
    networks:
      - frontend

  app_backend:
    build:
      context: ./culturalevents-backend
      dockerfile: Dockerfile
    container_name: app-cultural-events
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/cultural_events_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: prod
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8080"]
      timeout: 10s
      retries: 5
    networks:
      - backend
      - frontend

  mysqldb:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cultural_events_db
    restart: 'unless-stopped'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
  frontend:
